#!/bin/bash

pacman_conf="/etc/pacman.conf"
pacman_conf_cachyos="/etc/pacman-more.conf"
pacman_conf_path_backup="/etc/pacman.conf.bak"

try_v3() {

	exec /lib/ld-linux-x86-64.so.2 --help | grep "x86-64-v3 (supported, searched)" > /dev/null
    if [ $? -eq 0 ]; then
    	echo "x86-64-v3 is supported"

    	sed -i 's/Architecture = auto/#Architecture = auto/' $pacman_conf_cachyos
    	sed -i 's/#<disabled_v3>//g' $pacman_conf_cachyos
    	
    	echo "backup old config"
    	mv $pacman_conf $pacman_conf_path_backup
    	
    	echo "CachyOS -v3 Repo changed"
    	mv $pacman_conf_cachyos $pacman_conf
    	
    else
    	echo "x86-64-v3 is not supported"
    fi
}

try_v3
