# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Systemd services manipulation.
#
# This module can enable services, timers and targets for systemd
# (if packaging doesn't already do that). It can also
# disable services and targets as well as mask units.
#
# The order of operations is fixed.  Enable services, enable targets,
# enable timers, disable services, disable targets and finally apply masks.
---

# There are several configuration keys for this module:
# *services*, *targets*, *timers*, *disable*, *disable-targets* and *mask*.
# The value of each key is a list of entries. Each entry has two keys:
#   - *name* is the (string) name of the service or target that is being
#     changed. Use quotes. Don't include unit suffix in the name. For
#     example, it should be "NetworkManager", not "NetworkManager.service"
#   - *mandatory* is a boolean option, which states whether the change
#     must be done successfully. If systemd reports an error while changing
#     a mandatory entry, the installation will fail. When mandatory is false,
#     errors for that systemd unit are ignored. If mandatory
#     is not specified, the default is false.
#
# An entry may also be given as a single string, which is then
# interpreted as the name of the service. In this case, mandatory
# is also set to the default of false.
#
# Use [] to express an empty list.
services:
  - name: "NetworkManager"
    mandatory: false
  - name: "cups"
    mandatory: false
  - name: "avahi-daemon"
    mandatory: false
  - name: "systemd-timesyncd"
    mandatory: false
  - name: "power-profiles-daemon"
    mandatory: false
  - name: "vboxservice"
    mandatory: false
  - name: "vmtoolsd"
    mandatory: false
  - name: "vmware-vmblock-fuse"
    mandatory: false
  - name: "firewalld"
    mandatory: false
  - name: "zfs-import-cache"
    mandatory: false
  - name: "zfs-mount"
    mandatory: false

targets:
  - name: "zfs-import"
    mandatory: false
  - name: "zfs"
    mandatory: false

disable:
  - name:  "pacman-init"
    mandatory:  false

disable-targets:
  - name: "multi-user"
    mandatory:  false

mask: []
